_target_: lightning.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 10

accelerator: cpu
devices: 1

log_every_n_steps: 10

# sanity checks
fast_dev_run: False
num_sanity_val_steps: 2

# mixed precision for extra speed-up
# precision: 16

## Control how often to perform a validation
check_val_every_n_epoch: 1
# limit_val_batches: 100     # limit the number of validation batches. or use float to limit the percentage of batches
# val_check_interval: 2000   # check validation set every 1000 training batches in the current epoch

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

detect_anomaly: True

## Effective training techniques
gradient_clip_val: 1.0
gradient_clip_algorithm: norm   # or "value"
accumulate_grad_batches: 1

