# https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.StochasticWeightAveraging.html#pytorch_lightning.callbacks.StochasticWeightAveraging

stochastic_weight_avg:
  _target_: lightning.pytorch.callbacks.StochasticWeightAveraging
  swa_lrs: 1e-2