# @package _global_

# specify default configurations
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodule: trackml.yaml
  - model: next_module_prediction.yaml
  - callbacks: default.yaml
  - logger:  null  # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: gpu.yaml
  - paths: default.yaml
  - hydra: default.yaml

task_name: "gpt4tracking"